// Generated from the legacy Cyber School Manager menu map (426 pages, 23 modules).
// Areas: setup = legacy Master, transaction = legacy Transaction, report = legacy Report/Tools.

export type ModuleArea = "setup" | "transaction" | "report";

export interface ModulePage {
  area: ModuleArea;
  label: string;
  pageKey: string;
}

export interface ModuleDef {
  key: string;
  name: string;
  icon: string;
  route: string;
  navGroup: string;
  sortOrder: number;
  allowedRoles: string[];
  pages: ModulePage[];
}

export const AREA_LABELS: Record<ModuleArea, string> = {
  setup: "Setup",
  transaction: "Daily work",
  report: "Reports",
};

export const MODULE_CATALOGUE: ModuleDef[] = [
  {
    key: "enquiry",
    name: "Enquiry",
    icon: "Search",
    route: "/enquiry",
    navGroup: "Academics",
    sortOrder: 10,
    allowedRoles: ["super_admin", "school_owner", "school_admin", "principal", "teacher"],
    pages: [
      { area: "setup", label: "Interest Level", pageKey: "frmEnquiryInterestLevel" },
      { area: "setup", label: "Followup Status", pageKey: "frmEnquiryFollowup" },
      { area: "report", label: "Enquiry Dashboard", pageKey: "frmEnquiryDashBoard" },
      { area: "report", label: "Enquiry Report", pageKey: "frmReportEnquiry" },
      { area: "report", label: "Month Wise Report", pageKey: "frmReportEnquiryMonthWise" },
      { area: "report", label: "Follow Up Report", pageKey: "frmReportEnquiryFollowup" },
    ],
  },
  {
    key: "students",
    name: "Student Management",
    icon: "GraduationCap",
    route: "/students",
    navGroup: "Academics",
    sortOrder: 20,
    allowedRoles: ["super_admin", "school_owner", "school_admin", "principal", "teacher"],
    pages: [
      { area: "setup", label: "Category Master", pageKey: "frmcategorymaster" },
      { area: "setup", label: "Religion Master", pageKey: "frmreligionmaster" },
      { area: "setup", label: "Country Master", pageKey: "FrmCountryMaster" },
      { area: "setup", label: "State Master", pageKey: "frmstatemaster" },
      { area: "setup", label: "District Master", pageKey: "frmDistictmaster" },
      { area: "setup", label: "City Master", pageKey: "frmcitymaster" },
      { area: "setup", label: "Language Master", pageKey: "frmstudentlanguage" },
      { area: "setup", label: "House Master", pageKey: "frmhousemaster" },
      { area: "setup", label: "Blood Group Master", pageKey: "frmBloodGroupmaster" },
      { area: "setup", label: "Club Master", pageKey: "frmclubmaster" },
      { area: "setup", label: "Admission Test Master", pageKey: "frmAdmissionTestMaster" },
      { area: "setup", label: "Occupation Master", pageKey: "frmOccupationmaster" },
      { area: "setup", label: "Qualification Master", pageKey: "frmQualificationmaster" },
      { area: "setup", label: "Student Type Category", pageKey: "frmstudentTypeCategorymaster" },
      { area: "setup", label: "Student Type Master", pageKey: "frmstudenttype" },
      { area: "setup", label: "Nationality Master", pageKey: "frmnationalitymaster" },
      { area: "transaction", label: "Add Enquiry", pageKey: "frmAddEnquiry" },
      { area: "transaction", label: "Assign Concession Type", pageKey: "AssignConcessionType" },
      { area: "transaction", label: "Manage Enquiry", pageKey: "frmManageEnquiry" },
      { area: "transaction", label: "Student Registration", pageKey: "frmstudentregistration" },
      { area: "transaction", label: "Student Admission", pageKey: "frmstudentadmission" },
      { area: "transaction", label: "Student Update", pageKey: "frmStudentUpdateNew" },
      { area: "transaction", label: "Student Image Upload", pageKey: "StudentImageEdit" },
      { area: "transaction", label: "Student House Update", pageKey: "frmHouseClubChange" },
      { area: "transaction", label: "Student Roll No. Update", pageKey: "frmStudentRollNoUpdate" },
      { area: "transaction", label: "Admission Test Mark", pageKey: "frmAdmissionTestMarks" },
      { area: "transaction", label: "Student Test Mark", pageKey: "frmStudenttestmark" },
      { area: "transaction", label: "Activity Head", pageKey: "frmActivityDetail" },
      { area: "transaction", label: "Student Search", pageKey: "frmstudentsearch" },
      { area: "transaction", label: "Student Health", pageKey: "frmHealthMaster" },
      { area: "transaction", label: "Out Pass", pageKey: "frmOutPass" },
      { area: "transaction", label: "Section Change", pageKey: "frmSectionChange" },
      { area: "transaction", label: "Student Left/Block", pageKey: "frmStudentInActive_Left_Block" },
      { area: "transaction", label: "Student Info Approval", pageKey: "frmUserDetailApproval" },
      { area: "transaction", label: "Out Pass Approval", pageKey: "frmOutPassApproval" },
      { area: "report", label: "Attendance Report", pageKey: "frmStudentAttendanceReport" },
      { area: "report", label: "Student Dashboard", pageKey: "frmstudentdashboard" },
      { area: "report", label: "Student Registration Detail", pageKey: "FrmStudentRegistrrationprint" },
      { area: "report", label: "Student Reports", pageKey: "frmstudentreport" },
      { area: "report", label: "Gender Wise Reports", pageKey: "frmgenderwisesummery" },
      { area: "report", label: "Religion Wise Reports", pageKey: "frmreligionwisereport" },
      { area: "report", label: "Category Wise Reports", pageKey: "frmcategorywisereport" },
      { area: "report", label: "Birthday Reports", pageKey: "frmBirthdayReport" },
      { area: "report", label: "Student Health Reports", pageKey: "frmHealthStatusReport" },
      { area: "report", label: "Admission Test Result Reports", pageKey: "frmTestresultReport" },
      { area: "report", label: "Student Type Wise Summary", pageKey: "frmStudentTypeWiseSummary" },
      { area: "report", label: "Student Sibling Report", pageKey: "frmstudentsiblingreport" },
      { area: "report", label: "Admission Date Report", pageKey: "frmstudentdetailreport" },
      { area: "report", label: "Student Label Print", pageKey: "frmStudentLabelPrint" },
      { area: "report", label: "Admission/Withdrawl Register", pageKey: "frmAdmissionWithdrawlRegister" },
      { area: "report", label: "Age Wise Report", pageKey: "frmAgeReport" },
      { area: "report", label: "State Wise Student Report", pageKey: "StudentStraingthDetailReport" },
      { area: "report", label: "Student Documents", pageKey: "frmStudentDocumentReport" },
    ],
  },
  {
    key: "classes",
    name: "Class Management",
    icon: "LayoutGrid",
    route: "/classes",
    navGroup: "Academics",
    sortOrder: 30,
    allowedRoles: ["super_admin", "school_owner", "school_admin", "principal", "teacher"],
    pages: [
      { area: "setup", label: "Class Group Master", pageKey: "frmclassgroupmaster" },
      { area: "setup", label: "Class Master", pageKey: "frmClasses" },
      { area: "setup", label: "Section Master", pageKey: "frmsections" },
    ],
  },
  {
    key: "examinations",
    name: "Examinations",
    icon: "BookOpenCheck",
    route: "/examinations",
    navGroup: "Academics",
    sortOrder: 40,
    allowedRoles: ["super_admin", "school_owner", "school_admin", "principal", "teacher"],
    pages: [
      { area: "setup", label: "Subject Master", pageKey: "SubjectMaster" },
      { area: "setup", label: "Class Subject Master", pageKey: "ClassSubjects_New" },
      { area: "setup", label: "Co-Scholastic Header Master", pageKey: "CoScholasticHeadermaster" },
      { area: "setup", label: "Co-Scholastic Areas", pageKey: "CoScholasticCategoryMaster" },
      { area: "setup", label: "Co-Scholastic Activities", pageKey: "CoScholasticSkillMaster" },
      { area: "setup", label: "Exam Master", pageKey: "ExamMaster" },
      { area: "setup", label: "Coscholastic Class Skill", pageKey: "CoScholasticClassSubjects" },
      { area: "setup", label: "Grade Scale Master", pageKey: "GradePool" },
      { area: "setup", label: "Coscholastic Descriptors", pageKey: "CoScholasticDescriptors" },
      { area: "setup", label: "Class Subject Part", pageKey: "ClassSubjectPart" },
      { area: "setup", label: "Marks Entry Date Setting", pageKey: "MarksEntryDateSetting" },
      { area: "setup", label: "Exam Class Group Master", pageKey: "ExamClassGroupMaster" },
      { area: "setup", label: "Assign Subjects", pageKey: "AssignSubjects" },
      { area: "setup", label: "SubjectPart Order Settings", pageKey: "frmSubjectSubPartSequence" },
      { area: "setup", label: "Teacher Remarks Master", pageKey: "frmTeacherRemarksMaster_New" },
      { area: "setup", label: "Set Subject Sequence", pageKey: "frmSubjectSequence_new" },
      { area: "setup", label: "Subject Enrichment Activity", pageKey: "frmSubjectEnrichmentActivities" },
      { area: "setup", label: "Exam Settings", pageKey: "frmExamSettings" },
      { area: "transaction", label: "Student Subjects", pageKey: "StudentSubjects" },
      { area: "transaction", label: "Subject Mark Setting", pageKey: "SubjectMarksSetting" },
      { area: "transaction", label: "Subject Mark Obtained", pageKey: "StudentMarkObtained" },
      { area: "transaction", label: "Co-Scholastic Subject", pageKey: "frmStudentCo-ScholasticSubject" },
      { area: "transaction", label: "Student Accolades", pageKey: "StudentAccolades" },
      { area: "transaction", label: "Student Wise Mark Entry", pageKey: "frmStudentWiseMarkEntry" },
      { area: "transaction", label: "CoScholastic Performance", pageKey: "StudentsCoScholasticPerformance" },
      { area: "transaction", label: "Teacher Remarks", pageKey: "StudentRemarks" },
      { area: "transaction", label: "Student Remarks Subject Wise", pageKey: "StudentRemarksSubjectWise" },
      { area: "transaction", label: "Student Wise Remarks Entry", pageKey: "StudentWiseRemarksEntry" },
      { area: "transaction", label: "Remarks Type Mapping", pageKey: "ClassRemarkMapping" },
      { area: "transaction", label: "Student Result", pageKey: "StudentResult" },
      { area: "transaction", label: "Update Student Roll", pageKey: "frmupdatestudentRollNo" },
      { area: "report", label: "Report Card", pageKey: "frmReportCard" },
      { area: "report", label: "Student Subject Report", pageKey: "frmStudentSubjectReport" },
      { area: "report", label: "Marks Sheet", pageKey: "MarksSheet" },
      { area: "report", label: "Tabulation Report", pageKey: "frmTabulationReport" },
      { area: "report", label: "Exam Result", pageKey: "ExamResult" },
      { area: "report", label: "Failed Student List", pageKey: "FailedStudentList" },
      { area: "report", label: "Comparative Report", pageKey: "ComparativeReport" },
      { area: "report", label: "Student Remarks Report", pageKey: "StudentRemarksReport" },
      { area: "report", label: "Verify Student Data", pageKey: "Verifystudentdata" },
      { area: "report", label: "Subject Wise Graph", pageKey: "frmLineChart" },
      { area: "report", label: "Coscholastic Marksheet", pageKey: "CoscholasticMarksheet" },
      { area: "report", label: "Percentage Report", pageKey: "percentagereport" },
      { area: "report", label: "Exam Wise Report", pageKey: "frmexamwisereport" },
      { area: "report", label: "Subject Wise Strength", pageKey: "frmSubjectWiseStrength" },
      { area: "report", label: "Subject Wise Summary", pageKey: "frmSubjectwiseSummary" },
      { area: "report", label: "Result Class Wise", pageKey: "ResultClassWise" },
      { area: "report", label: "Class Wise Subject Report", pageKey: "frmClassWiseSubjectReport" },
      { area: "report", label: "Student Performance Graph", pageKey: "frmStudentPerformanceGraph" },
      { area: "report", label: "Consolidated Report", pageKey: "ConsolidatedReport" },
      { area: "report", label: "Class/Teacher Wise Subject", pageKey: "frmClassTeacherWiseSubjectDetail" },
      { area: "report", label: "Teacher Performance", pageKey: "frmTeacherPerformance" },
      { area: "report", label: "Subject Wise Performance", pageKey: "frmSubjectWisePerformance" },
      { area: "report", label: "CBSE Board Result Analysis", pageKey: "frmCBSEResultReportClass10" },
      { area: "report", label: "CBSE Reports", pageKey: "frmSubjectWiseComparativeReport" },
      { area: "report", label: "Exam Wise Teacher Performance", pageKey: "frmTeacherPerformance_New" },
      { area: "report", label: "SessionWise Teacher Performance", pageKey: "frmTeacherPerformance_SessionsComparitive" },
    ],
  },
  {
    key: "timetable",
    name: "Timetable",
    icon: "CalendarRange",
    route: "/timetable",
    navGroup: "Academics",
    sortOrder: 50,
    allowedRoles: ["super_admin", "school_owner", "school_admin", "principal", "teacher"],
    pages: [
      { area: "setup", label: "Employee Master", pageKey: "frmEmployeeMaster" },
      { area: "setup", label: "Class/Subject Issue To Teacher", pageKey: "ClassIssueToTeacher" },
      { area: "setup", label: "CoScholastic Subject Issue To Teacher", pageKey: "CoScholasticSubjectIssuesToTeacher_New" },
      { area: "setup", label: "Teacher Work Allotment", pageKey: "TeacherWorkAllotment" },
      { area: "setup", label: "Time Table Titles", pageKey: "frmtimetabletitle" },
      { area: "setup", label: "Class-Subject Grouping", pageKey: "frmClassSubjectGrouping" },
      { area: "setup", label: "Days Master", pageKey: "frmdaysmaster" },
      { area: "setup", label: "Venue Master", pageKey: "frmAddOuterMaster" },
      { area: "setup", label: "Period Timings Master", pageKey: "PeriodTimingsMaster" },
      { area: "setup", label: "Period Reservation", pageKey: "frmPeriodsReservation" },
      { area: "setup", label: "Venue Allocation", pageKey: "frmOuterAllocation" },
      { area: "setup", label: "Teacher-Wise Period/Days Lock", pageKey: "TeacherWisePeriodDaysLock" },
      { area: "setup", label: "Class-Wise Period/Days Lock", pageKey: "ClassWisePeriodDaysLock" },
      { area: "setup", label: "Double Period Rules", pageKey: "frmDoublePeriodRules" },
      { area: "transaction", label: "Generate TimeTable", pageKey: "frmGenerateAutomaticTimeTable" },
      { area: "transaction", label: "Absent Teacher Detail", pageKey: "Timetable_AbsentTeachers" },
      { area: "transaction", label: "Teacher Substitute", pageKey: "TeacherWiseTimeTableSubstitute" },
      { area: "transaction", label: "Class Wise Period Adjustments", pageKey: "frmTimeTableGenerationAuto" },
      { area: "transaction", label: "Import Allocation Data", pageKey: "frmuploadteachersdata" },
      { area: "report", label: "Teacher Work Detail", pageKey: "TeacherWorkDetail" },
      { area: "report", label: "Teacher Wise Class Subject", pageKey: "TeacherSubjectInformationInClass" },
      { area: "report", label: "Class Subject Information For Teacher", pageKey: "ClassSubjectInformationForTeacher" },
      { area: "report", label: "Teacher Work Not Allocated", pageKey: "TeacherWorkNotAllocated" },
      { area: "report", label: "Co-ordinator/Incharge Report", pageKey: "TeacherCordinatorReport" },
      { area: "report", label: "Subject Wise Teacher Allocations", pageKey: "frmsubjectwiseteacherallocations" },
      { area: "report", label: "Free Teachers Report", pageKey: "FreeTeachersTimeTableConsolidated" },
      { area: "report", label: "ClassWise TimeTable Report", pageKey: "PrintAllclasstimetablereport" },
      { area: "report", label: "Class Wise Time Table Consolidated", pageKey: "ClassWiseTimeTableConsolidated" },
      { area: "report", label: "Teacher Wise Time Table", pageKey: "TeacherwiseTimeTableReport" },
      { area: "report", label: "Teacher Wise Time Table Consolidated", pageKey: "TeacherWiseTimeTableConsolidated" },
      { area: "report", label: "Teacher Wise Auto Time Table", pageKey: "MasterAutoTimeTable" },
      { area: "report", label: "Subject Wise TimeTable", pageKey: "frmSubjectWiseTimeTableGenaration" },
      { area: "report", label: "Venue Wise TimeTable", pageKey: "frmVenueWiseTimeTableGenaration" },
      { area: "report", label: "Teacher-wise Daily Schedule", pageKey: "frmDays_PeriodsWiseTimeTableReport" },
      { area: "report", label: "Consolidated Time Table", pageKey: "frmTimetableConsolidatedReport" },
      { area: "report", label: "Monthly Teacher Substitution", pageKey: "Timetable_weeklysubstitutionreport" },
      { area: "report", label: "Monthly Teacher Leave Report", pageKey: "timetable_Monthlyteacherleavereport" },
      { area: "report", label: "Verify Logs", pageKey: "frmverifytimetablelogs" },
      { area: "report", label: "Clash Report", pageKey: "TimeTableClashsReport" },
    ],
  },
  {
    key: "attendance",
    name: "Attendance",
    icon: "CalendarCheck",
    route: "/attendance",
    navGroup: "Academics",
    sortOrder: 60,
    allowedRoles: ["super_admin", "school_owner", "school_admin", "principal", "teacher"],
    pages: [
      { area: "transaction", label: "Student Attendance TermWise", pageKey: "frmattendancetermwise" },
    ],
  },
  {
    key: "teacher-diary",
    name: "Teacher Diary",
    icon: "NotebookPen",
    route: "/teacher-diary",
    navGroup: "Academics",
    sortOrder: 70,
    allowedRoles: ["super_admin", "school_owner", "school_admin", "principal", "teacher"],
    pages: [
      { area: "setup", label: "Lesson Master", pageKey: "LessonMaster" },
      { area: "transaction", label: "Teaching Lesson Plan", pageKey: "TeachingLessonPlan" },
      { area: "transaction", label: "Lesson Plan Sign Verification", pageKey: "TeachingLessonPlanSignVerification" },
      { area: "transaction", label: "Gifted Student Entry", pageKey: "GiftedStudentEntry" },
      { area: "transaction", label: "Gifted Student Sign Verification", pageKey: "GiftedStudentSignVerification" },
      { area: "transaction", label: "Weak Student Entry", pageKey: "WeakStudentEntry" },
      { area: "transaction", label: "Weak Student Sign Verification", pageKey: "WeakStudentSignVerification" },
      { area: "transaction", label: "PTM Detail", pageKey: "PTMDetail" },
      { area: "transaction", label: "Teaching Proficiency", pageKey: "frmTeachingProficiency" },
      { area: "report", label: "Teaching Lesson Plan Report", pageKey: "TeachingLessonPlanReport" },
      { area: "report", label: "Gifted Student Sign Report", pageKey: "GiftedStudentSignReport" },
      { area: "report", label: "Weak Student Sign Report", pageKey: "WeakStudentSignReport" },
      { area: "report", label: "Employee BioData Report", pageKey: "frmEmployeeBioDataReport" },
      { area: "report", label: "Teaching Proficiency Report", pageKey: "frmTeachingProficiencyReport" },
    ],
  },
  {
    key: "competition",
    name: "Competition",
    icon: "Trophy",
    route: "/competition",
    navGroup: "Academics",
    sortOrder: 80,
    allowedRoles: ["super_admin", "school_owner", "school_admin", "principal", "teacher"],
    pages: [
      { area: "setup", label: "Competition Type", pageKey: "frmCompetitionType" },
      { area: "setup", label: "Participants Entry", pageKey: "frmParticipantsEntry" },
      { area: "setup", label: "Competition Category", pageKey: "frmCompetitionCategory" },
      { area: "setup", label: "Competition SubCategory", pageKey: "frmCompetitionSubCategory" },
      { area: "setup", label: "Competition Master", pageKey: "frmCompetitionMaster" },
      { area: "report", label: "Competition Reports", pageKey: "frmCompetationReport" },
      { area: "report", label: "Student Wise Competition Report", pageKey: "frmStudentWiseCompetationReport" },
    ],
  },
  {
    key: "medical",
    name: "Medical",
    icon: "Stethoscope",
    route: "/medical",
    navGroup: "Academics",
    sortOrder: 90,
    allowedRoles: ["super_admin", "school_owner", "school_admin", "principal", "teacher"],
    pages: [
      { area: "transaction", label: "Health Card", pageKey: "frmHealthAndActivityDetail" },
      { area: "transaction", label: "Medical Record Entry", pageKey: "frmMedicalrecordentry" },
      { area: "report", label: "Medical Record Report", pageKey: "frmmedicalRecordreport" },
    ],
  },
  {
    key: "fee",
    name: "Fee",
    icon: "IndianRupee",
    route: "/fee",
    navGroup: "Finance",
    sortOrder: 100,
    allowedRoles: ["super_admin", "school_owner", "school_admin", "principal", "accountant"],
    pages: [
      { area: "setup", label: "Fee Category Master", pageKey: "frmfeeCategorymaster" },
      { area: "setup", label: "Fee Head Master", pageKey: "frmfeeheadcreation" },
      { area: "setup", label: "Fee Month Setting", pageKey: "frmfeeMonths_new" },
      { area: "setup", label: "Class Fee Master", pageKey: "frmClassFeeMaster" },
      { area: "setup", label: "Fee Concession Master", pageKey: "frmconcession" },
      { area: "setup", label: "Fee Concession Detail", pageKey: "frmFeeConcessionDetail" },
      { area: "setup", label: "Student Concession", pageKey: "frmStudentConcession" },
      { area: "setup", label: "Manual Concession", pageKey: "frmStudentConcessionManual" },
      { area: "setup", label: "Fine Detail", pageKey: "frmfinedetail" },
      { area: "setup", label: "Payment Mode Master", pageKey: "frmpaymentmode" },
      { area: "setup", label: "Bank Master", pageKey: "frmBankMaster" },
      { area: "setup", label: "Expense Type Master", pageKey: "frmExpenseTypeMaster" },
      { area: "transaction", label: "Extra Fee", pageKey: "frmExtraFeeEntry" },
      { area: "transaction", label: "Miscellaneous Receipt", pageKey: "FrmMiscRecipt" },
      { area: "transaction", label: "Fee Receipt", pageKey: "frmFeeReceipt" },
      { area: "transaction", label: "Import Receipt (Excel)", pageKey: "ImportReceiptFromExcel" },
      { area: "transaction", label: "Fee Demand", pageKey: "frmFeeDemand" },
      { area: "transaction", label: "Fee Refund", pageKey: "frmSecurityRefund" },
      { area: "transaction", label: "Mid-Day Meal Attendance", pageKey: "frmAssignMidDayMeal" },
      { area: "transaction", label: "Student Activity Detail", pageKey: "frmStudentActivityDetail" },
      { area: "transaction", label: "Pocket Money", pageKey: "frmPocketMoney" },
      { area: "transaction", label: "Pocket Money Expenses", pageKey: "frmPocketMoneyExpenses" },
      { area: "transaction", label: "Employee Receipt", pageKey: "frmFeeReceiptEmp" },
      { area: "transaction", label: "Pocket Money Opening", pageKey: "frmPocketMoneyOpeningBalance" },
      { area: "transaction", label: "Fee Reconciliation", pageKey: "frmFeeReconciliation" },
      { area: "report", label: "Fee Structure", pageKey: "frmFeeStructure" },
      { area: "report", label: "Fee Report", pageKey: "frmFeeReport" },
      { area: "report", label: "Fee Receipt Summary", pageKey: "frmFeeReceiptSummary" },
      { area: "report", label: "Annual Fee Summary Report", pageKey: "frmFeeAnnualSummaryReport" },
      { area: "report", label: "Fee Concession Report", pageKey: "frmFeeConcessionReport" },
      { area: "report", label: "Fee Summary Report", pageKey: "frmFeeSummary" },
      { area: "report", label: "Fee Receipt Detail Summary", pageKey: "frmfeeReceiptDetailSummary" },
      { area: "report", label: "Students Fee Months", pageKey: "frmDiscountReport" },
      { area: "report", label: "Date Wise Summary", pageKey: "frmDateWiseSummary" },
      { area: "report", label: "Fee Settlement Report", pageKey: "frmFeeSettlementReport" },
      { area: "report", label: "Miscellaneous Receipt", pageKey: "frmMiscellaneousReceiptReport" },
      { area: "report", label: "Registration Receipt", pageKey: "frmregistrationreciept" },
      { area: "report", label: "Fee Register Receipt", pageKey: "frmFeeRegister" },
      { area: "report", label: "Class Wise Fee Report", pageKey: "frmClassWiseFeeReport" },
      { area: "report", label: "Fee Refund Report", pageKey: "frmSecurityRefundReport" },
      { area: "report", label: "Fee Defaulters", pageKey: "frmFeeDefaulters" },
      { area: "report", label: "Fee Detail Class/Date Wise", pageKey: "frmFeeDetailDateWise" },
      { area: "report", label: "Student Fee Ledger", pageKey: "frmStudentFeeSummary" },
      { area: "report", label: "Mid-Day Meal Report", pageKey: "frmMidDayMealReport" },
      { area: "report", label: "Student Fee Summary", pageKey: "frmfeesummarydetail" },
      { area: "report", label: "Monthly Fee Collection", pageKey: "frmMonthlyFeeCollection" },
      { area: "report", label: "Cancel Fee Report", pageKey: "frmCancelledFeeReport" },
      { area: "report", label: "Daily Fee Collection", pageKey: "frmFeeDailyCollectionReport" },
      { area: "report", label: "Pocket Money Balance", pageKey: "frmPocketMoneyBalanceReport" },
      { area: "report", label: "Full Year Payment Report", pageKey: "frmFullYearPaymentReport" },
      { area: "report", label: "Student Activity Report", pageKey: "frmFeeActivityReport" },
      { area: "report", label: "Extra Fee Detail Report", pageKey: "frmStudentFeeDetailsWithRemarks" },
    ],
  },
  {
    key: "accounts",
    name: "Accounts",
    icon: "Calculator",
    route: "/accounts",
    navGroup: "Finance",
    sortOrder: 110,
    allowedRoles: ["super_admin", "school_owner", "school_admin", "principal", "accountant"],
    pages: [
      { area: "setup", label: "Ledger Groups", pageKey: "LedgerGroupMaster" },
      { area: "setup", label: "Ledgers", pageKey: "LedgersMaster" },
      { area: "setup", label: "Ledger Openings", pageKey: "AccountOpening" },
      { area: "setup", label: "Map Fee Heads", pageKey: "frmMapFeeHeads" },
      { area: "setup", label: "Map Payment Mode Heads", pageKey: "frmMapPaymentModeHeads" },
      { area: "setup", label: "Map Other Heads", pageKey: "frmMapOtherHeads" },
      { area: "transaction", label: "Account Voucher", pageKey: "AccountVouchers" },
      { area: "transaction", label: "Recycle Bin Account Vouchers", pageKey: "AccountVoucherRecycleBin" },
      { area: "transaction", label: "Stock Ledgers Closing", pageKey: "StockLedgersClosing" },
      { area: "transaction", label: "Generate Demand", pageKey: "GeneralDemand" },
      { area: "transaction", label: "Approve Demand", pageKey: "ApproveGeneralDemand" },
      { area: "transaction", label: "Bank Reconciliation", pageKey: "BankReconciliation" },
      { area: "report", label: "Ledger Accounts", pageKey: "AccountsLedgers" },
      { area: "report", label: "Ledger Account Detail", pageKey: "AccountsLedgersDetail" },
      { area: "report", label: "Date Wise Ledger Accounts", pageKey: "AccountsLedgersDateWise" },
      { area: "report", label: "Month Wise Ledger Accounts", pageKey: "AccountsLedgersMonthWise" },
      { area: "report", label: "Cash Book", pageKey: "CashBook" },
      { area: "report", label: "Day Book", pageKey: "DayBook" },
      { area: "report", label: "Trial Balance", pageKey: "TrialBalance" },
      { area: "report", label: "Balance Sheet", pageKey: "BalanceSheet" },
      { area: "report", label: "Accounts Vouchers List", pageKey: "AccountVoucherDetailList" },
      { area: "report", label: "Income Expenditure Report", pageKey: "IncomeExpenditure" },
      { area: "report", label: "Profit & Loss Statement", pageKey: "ProfitAndLossStatement" },
      { area: "report", label: "Bank Reconciliation Statement", pageKey: "BankReconciliationStatement" },
    ],
  },
  {
    key: "payroll",
    name: "Payroll",
    icon: "Wallet",
    route: "/payroll",
    navGroup: "Finance",
    sortOrder: 120,
    allowedRoles: ["super_admin", "school_owner", "school_admin", "principal", "accountant"],
    pages: [
      { area: "setup", label: "Designation Master", pageKey: "frmDesignationmaster" },
      { area: "setup", label: "Department Master", pageKey: "frmDepartmentmaster" },
      { area: "setup", label: "Salary Head Master", pageKey: "SalaryHeadMaster" },
      { area: "setup", label: "Salary Head Dependancy", pageKey: "SalaryHeadDependancy" },
      { area: "setup", label: "PF Settings", pageKey: "PFSettings" },
      { area: "setup", label: "ESI Settings", pageKey: "ESiSettings" },
      { area: "setup", label: "Pay Level Master", pageKey: "frmPayLevelmaster" },
      { area: "setup", label: "Employee Detail", pageKey: "frmEmployeeDetail" },
      { area: "setup", label: "Other Salary Head Settings", pageKey: "OtherSalaryHeadSettings" },
      { area: "setup", label: "Salary Increment Settings", pageKey: "SalaryIncrementSettings" },
      { area: "setup", label: "Grade Pay Settings", pageKey: "RevisedGradePaySettings" },
      { area: "setup", label: "Bank Statement Settings", pageKey: "BankSettings" },
      { area: "setup", label: "Employee Category", pageKey: "EmployeeTypeMaster" },
      { area: "setup", label: "State Master", pageKey: "StateMaster" },
      { area: "setup", label: "City Master", pageKey: "CityMaster" },
      { area: "setup", label: "Country Master", pageKey: "CountryMaster" },
      { area: "setup", label: "Branch Master", pageKey: "BranchMaster" },
      { area: "setup", label: "Designation Wise Scale Settings", pageKey: "GradeScaleSettings" },
      { area: "setup", label: "Increment Settings", pageKey: "AnnualIncrement" },
      { area: "transaction", label: "Attendance Monthly", pageKey: "AttendanceEmployeeMonthly" },
      { area: "transaction", label: "Salary Generation", pageKey: "SalaryGenrationN" },
      { area: "transaction", label: "Publish Salary Slips", pageKey: "PublishSalary" },
      { area: "report", label: "EPF Report", pageKey: "EPFReportMonthly" },
      { area: "report", label: "Salary Certificate", pageKey: "SalaryCertificate" },
      { area: "report", label: "Salary Report", pageKey: "SalarySlip" },
      { area: "report", label: "Bank Statement", pageKey: "BankStatement" },
      { area: "report", label: "Employee Salary Slip", pageKey: "SalarySlipEmployee" },
      { area: "report", label: "Employee Detail", pageKey: "EmpDetail" },
      { area: "report", label: "ESI Report", pageKey: "ESIReportMonthly" },
      { area: "report", label: "Head Wise Report", pageKey: "SalaryHeadWiseReport" },
      { area: "report", label: "Employee Documents", pageKey: "frmEmployeeDocumentsReport" },
    ],
  },
  {
    key: "transport",
    name: "Transport",
    icon: "Bus",
    route: "/transport",
    navGroup: "Operations",
    sortOrder: 130,
    allowedRoles: ["super_admin", "school_owner", "school_admin", "principal", "transport_staff"],
    pages: [
      { area: "setup", label: "Station Master", pageKey: "frmstationmaster" },
      { area: "setup", label: "PickUp Point Master", pageKey: "frmpicuppointmaster" },
      { area: "setup", label: "Route Master", pageKey: "frmroutemaster" },
      { area: "setup", label: "Transport Charges", pageKey: "frmTransportCharges" },
      { area: "setup", label: "Vehicle Master", pageKey: "frmVehiclemaster" },
      { area: "setup", label: "Vehicle Driver Master", pageKey: "frmVehicledrivermaster" },
      { area: "setup", label: "Vehicle Track Links", pageKey: "frmVehicleTrackMaster" },
      { area: "setup", label: "Vehicle Route Detail Master", pageKey: "frmVehicleRouteDetail" },
      { area: "setup", label: "Insurance Company Master", pageKey: "frmInsuranceCompanyMaster" },
      { area: "setup", label: "Insurance Type Master", pageKey: "frmInsuranceTypeMaster" },
      { area: "setup", label: "Vehicle Timing", pageKey: "frmVehicleTiming" },
      { area: "transaction", label: "Assign Transport", pageKey: "frmAssignTransport" },
      { area: "transaction", label: "Leave Transport", pageKey: "frmLeaveTransport" },
      { area: "transaction", label: "Road Tax Detail", pageKey: "frmVehicleRoadTax" },
      { area: "transaction", label: "Vehicle Detail", pageKey: "frmvehicleDetail" },
      { area: "transaction", label: "Vehicle Log Entry", pageKey: "frmVehicleLogEntry" },
      { area: "transaction", label: "DG/Elec. Log Entry", pageKey: "frmLogEntry" },
      { area: "transaction", label: "Vehicle Maintenance", pageKey: "frmVehicleMaintenance" },
      { area: "report", label: "Student Transport Reports", pageKey: "frmstudenttransportreport" },
      { area: "report", label: "Transport Leave Report", pageKey: "frmTransportLeaveReport" },
      { area: "report", label: "Transport MonthWise", pageKey: "frmtransportPrintmonthwise" },
      { area: "report", label: "Transport Strength Summary", pageKey: "frmTransportStrengthSummary" },
      { area: "report", label: "Vehicle Wise Report", pageKey: "frmtransportVehiclewisereport" },
      { area: "report", label: "Station Charges Report", pageKey: "frmStationChargesReport" },
      { area: "report", label: "Class Wise Transport Summary", pageKey: "frmClassWiseTransportSummary" },
      { area: "report", label: "Vehicle Revenue Report", pageKey: "VehicleRevenueReport" },
      { area: "report", label: "Vehicle Log Entry Report", pageKey: "frmVehicleLogEntryReport" },
      { area: "report", label: "Vehicle Expenses Report", pageKey: "frmVehicleExpensesComparision" },
      { area: "report", label: "Employee Transport Report", pageKey: "frmEmployeeTransportReport" },
      { area: "report", label: "DG/Elec. Log Entry Report", pageKey: "frmLogEntryReport" },
      { area: "report", label: "Vehicle Maintenance Report", pageKey: "frmVehicleMaintenanceReport" },
    ],
  },
  {
    key: "library",
    name: "Library",
    icon: "Library",
    route: "/library",
    navGroup: "Operations",
    sortOrder: 140,
    allowedRoles: ["super_admin", "school_owner", "school_admin", "principal", "librarian", "teacher"],
    pages: [
      { area: "setup", label: "Book Category", pageKey: "frmBookCategory" },
      { area: "setup", label: "Book Sub Category", pageKey: "frmBookSubCategory" },
      { area: "setup", label: "Book Publisher", pageKey: "frmBookPublisher" },
      { area: "setup", label: "Library Master", pageKey: "frmLibraryMaster" },
      { area: "setup", label: "Library Rack Master", pageKey: "frmLibraryRackMaster" },
      { area: "setup", label: "Library Shelf Master", pageKey: "frmLibraryShelfMaster" },
      { area: "setup", label: "Book Size Master", pageKey: "frmbooksize" },
      { area: "setup", label: "Book Cover Type Master", pageKey: "frmbookcovertype" },
      { area: "setup", label: "Book Author Master", pageKey: "frmbookauthor" },
      { area: "setup", label: "Book Edition Master", pageKey: "FrmBookEditionMaster" },
      { area: "setup", label: "Volume Master", pageKey: "FrmVolumeMaster" },
      { area: "setup", label: "Book Language Master", pageKey: "frmBookLanguageMaster" },
      { area: "setup", label: "Book Master", pageKey: "frmBookMaster_New" },
      { area: "setup", label: "Book Issue Period Master", pageKey: "frmbookissue" },
      { area: "setup", label: "Periodical Master", pageKey: "frmPeriodicalMaster" },
      { area: "setup", label: "Library Stock Verification", pageKey: "frmLibraryStockVerification" },
      { area: "transaction", label: "Book Issue", pageKey: "frmBookIssueDetail" },
      { area: "transaction", label: "Book Return", pageKey: "frmBookReturnDetail" },
      { area: "transaction", label: "Book Demand", pageKey: "frmlibraybookdemand" },
      { area: "transaction", label: "Book Purchase", pageKey: "frmbookpurchase" },
      { area: "transaction", label: "Book Dispose", pageKey: "frmBookDispose" },
      { area: "transaction", label: "Library Attendance", pageKey: "frmlibraryattendance" },
      { area: "transaction", label: "Periodical Issue", pageKey: "frmPeriodicalIssue" },
      { area: "transaction", label: "Periodical Return", pageKey: "frmPeriodicalReturn" },
      { area: "report", label: "Book Issued Report", pageKey: "frmissuereport" },
      { area: "report", label: "Library Book History", pageKey: "AccWiseBookHistory" },
      { area: "report", label: "Book Return Report", pageKey: "frmreturnbookreport" },
      { area: "report", label: "Pending Book Report", pageKey: "frmbookduereport" },
      { area: "report", label: "Book Information", pageKey: "frmbookInformation" },
      { area: "report", label: "Book Dispose Report", pageKey: "frmbookdisposeReport" },
      { area: "report", label: "Periodical Report", pageKey: "frmPerdicalReport" },
      { area: "report", label: "Stock Verification Report", pageKey: "frmStockVerficationreport" },
      { area: "report", label: "Issue Habit Report", pageKey: "frmissuehabitreport" },
      { area: "report", label: "Library Reading Habit Report", pageKey: "frmIssueReadingHabitreport" },
      { area: "report", label: "Library Attendance Report", pageKey: "FrmLibraryReport" },
      { area: "report", label: "Library Catalogue", pageKey: "frmLibraryCatalogue" },
      { area: "report", label: "Library Fine Report", pageKey: "frmLibraryFineReport" },
    ],
  },
  {
    key: "hostel",
    name: "Hostel",
    icon: "BedDouble",
    route: "/hostel",
    navGroup: "Operations",
    sortOrder: 150,
    allowedRoles: ["super_admin", "school_owner", "school_admin", "principal", "hostel_staff"],
    pages: [
      { area: "setup", label: "Hostel Master", pageKey: "frmHostelMaster" },
      { area: "setup", label: "Room Type Master", pageKey: "frmHostelRoomTypeMaster" },
      { area: "setup", label: "Floor Master", pageKey: "frmHostelFloorMaster" },
      { area: "setup", label: "Amenity Master", pageKey: "frmHostelAmenityMaster" },
      { area: "setup", label: "Room Master", pageKey: "frmHostelRoomMaster" },
      { area: "setup", label: "Hostel Fee Structure", pageKey: "frmHostelFeeStructure" },
      { area: "setup", label: "Mess Master", pageKey: "frmHostelMessMaster" },
      { area: "setup", label: "Hostel Meal Amount Master", pageKey: "frmHostelMealAmountMaster" },
      { area: "transaction", label: "Room Allocation", pageKey: "frmHostelRoomAllocation" },
      { area: "transaction", label: "Room Shifting", pageKey: "frmHostelRoomShifting" },
      { area: "transaction", label: "Leave Hostel", pageKey: "frmLeaveHostel" },
      { area: "transaction", label: "Outing Register", pageKey: "frmHostelOutingRegister" },
      { area: "report", label: "HostelWise Room Details", pageKey: "frmHostelRoomDetails" },
      { area: "report", label: "Room Wise Amenity Detail", pageKey: "frmHostelRoomAmenityDetails" },
      { area: "report", label: "Room Wise Student Detail", pageKey: "frmHostelRoomWiseStudentDetails" },
      { area: "report", label: "Hosteler Detail", pageKey: "frmHostelerDetails" },
      { area: "report", label: "Left Hostel Report", pageKey: "frmHostelLeftReport" },
      { area: "report", label: "Hostel Mess Amount Report", pageKey: "frmHostelMessAmountReport" },
    ],
  },
  {
    key: "inventory",
    name: "Inventory",
    icon: "Package",
    route: "/inventory",
    navGroup: "Operations",
    sortOrder: 160,
    allowedRoles: ["super_admin", "school_owner", "school_admin", "principal", "staff"],
    pages: [
      { area: "setup", label: "Item Type Master", pageKey: "ItemTypeMaster" },
      { area: "setup", label: "Unit Master", pageKey: "UnitMaster" },
      { area: "setup", label: "Tax Master", pageKey: "TaxMaster" },
      { area: "setup", label: "Item Master", pageKey: "ItemMaster" },
      { area: "transaction", label: "Stock In", pageKey: "StockInUpdated" },
      { area: "transaction", label: "Issue Stock", pageKey: "SaleStock" },
      { area: "transaction", label: "Write Off Items", pageKey: "frmWriteOffItems" },
      { area: "transaction", label: "Generate Demand", pageKey: "frmDemandGeneration" },
      { area: "transaction", label: "Item Consumption", pageKey: "frmConsumptionGenerate" },
      { area: "report", label: "STB Report", pageKey: "Stb_Report_Latest" },
      { area: "report", label: "Daily Stock Issue Report", pageKey: "SaleStockDetail" },
      { area: "report", label: "Stock Purchase Report", pageKey: "frmItem_PurchaseReport" },
      { area: "report", label: "Stock In & Out Report", pageKey: "frmstock_in_out" },
      { area: "report", label: "Cancel Issue Stock Report", pageKey: "CancelIssueStockDetail" },
      { area: "report", label: "Student Wise Report", pageKey: "frmStudentWiseReport" },
    ],
  },
  {
    key: "events",
    name: "Event Management",
    icon: "PartyPopper",
    route: "/events",
    navGroup: "Operations",
    sortOrder: 170,
    allowedRoles: ["super_admin", "school_owner", "school_admin", "principal", "teacher"],
    pages: [
      { area: "transaction", label: "Nature of the Day", pageKey: "frmNatureoftheDay" },
    ],
  },
  {
    key: "hr",
    name: "HR",
    icon: "Users",
    route: "/hr",
    navGroup: "People",
    sortOrder: 180,
    allowedRoles: ["super_admin", "school_owner", "school_admin", "principal", "staff"],
    pages: [
      { area: "setup", label: "Employee Timings", pageKey: "frmEmpTimingMaster" },
      { area: "setup", label: "Employee Leave Authority", pageKey: "frmManageEmpLeaveAuthority" },
      { area: "transaction", label: "Employee Leave Entry", pageKey: "frmEmpLeaveEntry" },
      { area: "transaction", label: "Employee Manual Attendance", pageKey: "frmEmpOnDutyEntry" },
      { area: "transaction", label: "Employee Out Pass", pageKey: "frmEmployeeOutPass" },
      { area: "report", label: "Employee Attendance Report", pageKey: "frmEmpAttendanceReport" },
      { area: "report", label: "Employee Attendance Log", pageKey: "frmEmpAttendanceLogReport" },
    ],
  },
  {
    key: "interviews",
    name: "Interview Candidates",
    icon: "UserSearch",
    route: "/interviews",
    navGroup: "People",
    sortOrder: 190,
    allowedRoles: ["super_admin", "school_owner", "school_admin", "principal"],
    pages: [
      { area: "transaction", label: "Interviewer Details", pageKey: "InterviewerDetails" },
      { area: "report", label: "Interviewer Detail Report", pageKey: "InterviewerDetailReport" },
    ],
  },
  {
    key: "sms",
    name: "SMS & Notices",
    icon: "MessageSquare",
    route: "/communication",
    navGroup: "Communication",
    sortOrder: 200,
    allowedRoles: ["super_admin", "school_owner", "school_admin", "principal", "teacher"],
    pages: [
      { area: "setup", label: "SMS Configuration", pageKey: "frmAutoSMSConfiguration" },
      { area: "transaction", label: "Send SMS", pageKey: "frmsendsms" },
      { area: "transaction", label: "View Transaction SMS Detail", pageKey: "frmsendpendingsms" },
      { area: "report", label: "Sent SMS Reports", pageKey: "frmSentSMSReport" },
    ],
  },
  {
    key: "certificates",
    name: "Certificates",
    icon: "BadgeCheck",
    route: "/certificates",
    navGroup: "Communication",
    sortOrder: 210,
    allowedRoles: ["super_admin", "school_owner", "school_admin", "principal"],
    pages: [
      { area: "transaction", label: "Issue Certificate", pageKey: "frmIssuecertificate" },
      { area: "transaction", label: "Id Card Generation", pageKey: "frmIdCardGenerate" },
    ],
  },
  {
    key: "securities",
    name: "Securities",
    icon: "ShieldCheck",
    route: "/securities",
    navGroup: "Settings",
    sortOrder: 220,
    allowedRoles: ["super_admin", "school_owner", "school_admin", "principal"],
    pages: [
      { area: "setup", label: "User Profile", pageKey: "frmSecurityMaster" },
      { area: "setup", label: "User Master", pageKey: "frmuserMaster" },
      { area: "setup", label: "User Details", pageKey: "frmuserdetail" },
      { area: "setup", label: "School Information", pageKey: "FrmschoolInfo" },
      { area: "setup", label: "Admission No. Format", pageKey: "frmAdmissionNoFormat" },
      { area: "setup", label: "SMS Configuration", pageKey: "frmSMSsettings" },
      { area: "transaction", label: "Change Password", pageKey: "frmChangepwd" },
      { area: "transaction", label: "RollOver Fee Balance HeadWise", pageKey: "RollOverBalance_HeadWise" },
      { area: "transaction", label: "RollOver Data", pageKey: "RollOverData" },
      { area: "transaction", label: "Upload Data", pageKey: "frmUploadData" },
      { area: "transaction", label: "Transfer Student", pageKey: "frmTransferStudent" },
      { area: "report", label: "User LogIn Logs", pageKey: "frmUserLogDetails" },
    ],
  },
  {
    key: "settings",
    name: "Settings",
    icon: "Settings",
    route: "/settings",
    navGroup: "Settings",
    sortOrder: 230,
    allowedRoles: ["super_admin", "school_owner", "school_admin", "principal"],
    pages: [
      { area: "setup", label: "Report Templates", pageKey: "frmReportTemplates" },
      { area: "setup", label: "Application Approval Settings", pageKey: "frmApplicationApprovalSettings" },
      { area: "setup", label: "General Settings", pageKey: "GeneralSettings" },
      { area: "setup", label: "Assign App Menu To User", pageKey: "frmTeacherAppMenueRights" },
      { area: "setup", label: "School Bank Detail", pageKey: "frmschoolbankmaster" },
      { area: "transaction", label: "Publish Result", pageKey: "ResultPublish" },
      { area: "transaction", label: "Block Result", pageKey: "frmStudentResultBlock" },
    ],
  },
];

export const MODULE_BY_KEY: Record<string, ModuleDef> = Object.fromEntries(
  MODULE_CATALOGUE.map((m) => [m.key, m]),
);

export function pagesByArea(mod: ModuleDef) {
  return (["setup", "transaction", "report"] as const)
    .map((area) => ({ area, pages: mod.pages.filter((p) => p.area === area) }))
    .filter((g) => g.pages.length > 0);
}
