/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as AuthenticatedAccountsRouteImport } from './routes/_authenticated/accounts'
import { Route as AuthenticatedAttendanceRouteImport } from './routes/_authenticated/attendance'
import { Route as AuthenticatedCertificatesRouteImport } from './routes/_authenticated/certificates'
import { Route as AuthenticatedClassesRouteImport } from './routes/_authenticated/classes'
import { Route as AuthenticatedCommunicationRouteImport } from './routes/_authenticated/communication'
import { Route as AuthenticatedCompetitionRouteImport } from './routes/_authenticated/competition'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedEnquiryRouteImport } from './routes/_authenticated/enquiry'
import { Route as AuthenticatedEventsRouteImport } from './routes/_authenticated/events'
import { Route as AuthenticatedExaminationsRouteImport } from './routes/_authenticated/examinations'
import { Route as AuthenticatedFeeRouteImport } from './routes/_authenticated/fee'
import { Route as AuthenticatedHostelRouteImport } from './routes/_authenticated/hostel'
import { Route as AuthenticatedHrRouteImport } from './routes/_authenticated/hr'
import { Route as AuthenticatedInterviewsRouteImport } from './routes/_authenticated/interviews'
import { Route as AuthenticatedInventoryRouteImport } from './routes/_authenticated/inventory'
import { Route as AuthenticatedLibraryRouteImport } from './routes/_authenticated/library'
import { Route as AuthenticatedMedicalRouteImport } from './routes/_authenticated/medical'
import { Route as AuthenticatedPayrollRouteImport } from './routes/_authenticated/payroll'
import { Route as AuthenticatedSecuritiesRouteImport } from './routes/_authenticated/securities'
import { Route as AuthenticatedStudentsRouteImport } from './routes/_authenticated/students'
import { Route as AuthenticatedTeacherDiaryRouteImport } from './routes/_authenticated/teacher-diary'
import { Route as AuthenticatedTimetableRouteImport } from './routes/_authenticated/timetable'
import { Route as AuthenticatedTransportRouteImport } from './routes/_authenticated/transport'
import { Route as AuthSchoolRouteImport } from './routes/auth_.$school'
import { Route as AuthenticatedSettingsIndexRouteImport } from './routes/_authenticated/settings/index'
import { Route as AuthenticatedMModulePageRouteImport } from './routes/_authenticated/m.$module.$page'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAccountsRoute = AuthenticatedAccountsRouteImport.update({
  id: '/accounts',
  path: '/accounts',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAttendanceRoute = AuthenticatedAttendanceRouteImport.update({
  id: '/attendance',
  path: '/attendance',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedCertificatesRoute =
  AuthenticatedCertificatesRouteImport.update({
    id: '/certificates',
    path: '/certificates',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedClassesRoute = AuthenticatedClassesRouteImport.update({
  id: '/classes',
  path: '/classes',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedCommunicationRoute =
  AuthenticatedCommunicationRouteImport.update({
    id: '/communication',
    path: '/communication',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedCompetitionRoute =
  AuthenticatedCompetitionRouteImport.update({
    id: '/competition',
    path: '/competition',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedEnquiryRoute = AuthenticatedEnquiryRouteImport.update({
  id: '/enquiry',
  path: '/enquiry',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedEventsRoute = AuthenticatedEventsRouteImport.update({
  id: '/events',
  path: '/events',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedExaminationsRoute =
  AuthenticatedExaminationsRouteImport.update({
    id: '/examinations',
    path: '/examinations',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedFeeRoute = AuthenticatedFeeRouteImport.update({
  id: '/fee',
  path: '/fee',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedHostelRoute = AuthenticatedHostelRouteImport.update({
  id: '/hostel',
  path: '/hostel',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedHrRoute = AuthenticatedHrRouteImport.update({
  id: '/hr',
  path: '/hr',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedInterviewsRoute = AuthenticatedInterviewsRouteImport.update({
  id: '/interviews',
  path: '/interviews',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedInventoryRoute = AuthenticatedInventoryRouteImport.update({
  id: '/inventory',
  path: '/inventory',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedLibraryRoute = AuthenticatedLibraryRouteImport.update({
  id: '/library',
  path: '/library',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedMedicalRoute = AuthenticatedMedicalRouteImport.update({
  id: '/medical',
  path: '/medical',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedPayrollRoute = AuthenticatedPayrollRouteImport.update({
  id: '/payroll',
  path: '/payroll',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSecuritiesRoute = AuthenticatedSecuritiesRouteImport.update({
  id: '/securities',
  path: '/securities',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedStudentsRoute = AuthenticatedStudentsRouteImport.update({
  id: '/students',
  path: '/students',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedTeacherDiaryRoute =
  AuthenticatedTeacherDiaryRouteImport.update({
    id: '/teacher-diary',
    path: '/teacher-diary',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedTimetableRoute = AuthenticatedTimetableRouteImport.update({
  id: '/timetable',
  path: '/timetable',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedTransportRoute = AuthenticatedTransportRouteImport.update({
  id: '/transport',
  path: '/transport',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthSchoolRoute = AuthSchoolRouteImport.update({
  id: '/auth_/$school',
  path: '/auth/$school',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedSettingsIndexRoute =
  AuthenticatedSettingsIndexRouteImport.update({
    id: '/settings/',
    path: '/settings/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedMModulePageRoute =
  AuthenticatedMModulePageRouteImport.update({
    id: '/m/$module/$page',
    path: '/m/$module/$page',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/reset-password': typeof ResetPasswordRoute
  '/accounts': typeof AuthenticatedAccountsRoute
  '/attendance': typeof AuthenticatedAttendanceRoute
  '/certificates': typeof AuthenticatedCertificatesRoute
  '/classes': typeof AuthenticatedClassesRoute
  '/communication': typeof AuthenticatedCommunicationRoute
  '/competition': typeof AuthenticatedCompetitionRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/enquiry': typeof AuthenticatedEnquiryRoute
  '/events': typeof AuthenticatedEventsRoute
  '/examinations': typeof AuthenticatedExaminationsRoute
  '/fee': typeof AuthenticatedFeeRoute
  '/hostel': typeof AuthenticatedHostelRoute
  '/hr': typeof AuthenticatedHrRoute
  '/interviews': typeof AuthenticatedInterviewsRoute
  '/inventory': typeof AuthenticatedInventoryRoute
  '/library': typeof AuthenticatedLibraryRoute
  '/medical': typeof AuthenticatedMedicalRoute
  '/payroll': typeof AuthenticatedPayrollRoute
  '/securities': typeof AuthenticatedSecuritiesRoute
  '/students': typeof AuthenticatedStudentsRoute
  '/teacher-diary': typeof AuthenticatedTeacherDiaryRoute
  '/timetable': typeof AuthenticatedTimetableRoute
  '/transport': typeof AuthenticatedTransportRoute
  '/auth/$school': typeof AuthSchoolRoute
  '/settings/': typeof AuthenticatedSettingsIndexRoute
  '/m/$module/$page': typeof AuthenticatedMModulePageRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/reset-password': typeof ResetPasswordRoute
  '/accounts': typeof AuthenticatedAccountsRoute
  '/attendance': typeof AuthenticatedAttendanceRoute
  '/certificates': typeof AuthenticatedCertificatesRoute
  '/classes': typeof AuthenticatedClassesRoute
  '/communication': typeof AuthenticatedCommunicationRoute
  '/competition': typeof AuthenticatedCompetitionRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/enquiry': typeof AuthenticatedEnquiryRoute
  '/events': typeof AuthenticatedEventsRoute
  '/examinations': typeof AuthenticatedExaminationsRoute
  '/fee': typeof AuthenticatedFeeRoute
  '/hostel': typeof AuthenticatedHostelRoute
  '/hr': typeof AuthenticatedHrRoute
  '/interviews': typeof AuthenticatedInterviewsRoute
  '/inventory': typeof AuthenticatedInventoryRoute
  '/library': typeof AuthenticatedLibraryRoute
  '/medical': typeof AuthenticatedMedicalRoute
  '/payroll': typeof AuthenticatedPayrollRoute
  '/securities': typeof AuthenticatedSecuritiesRoute
  '/students': typeof AuthenticatedStudentsRoute
  '/teacher-diary': typeof AuthenticatedTeacherDiaryRoute
  '/timetable': typeof AuthenticatedTimetableRoute
  '/transport': typeof AuthenticatedTransportRoute
  '/auth/$school': typeof AuthSchoolRoute
  '/settings': typeof AuthenticatedSettingsIndexRoute
  '/m/$module/$page': typeof AuthenticatedMModulePageRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/reset-password': typeof ResetPasswordRoute
  '/_authenticated/accounts': typeof AuthenticatedAccountsRoute
  '/_authenticated/attendance': typeof AuthenticatedAttendanceRoute
  '/_authenticated/certificates': typeof AuthenticatedCertificatesRoute
  '/_authenticated/classes': typeof AuthenticatedClassesRoute
  '/_authenticated/communication': typeof AuthenticatedCommunicationRoute
  '/_authenticated/competition': typeof AuthenticatedCompetitionRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/enquiry': typeof AuthenticatedEnquiryRoute
  '/_authenticated/events': typeof AuthenticatedEventsRoute
  '/_authenticated/examinations': typeof AuthenticatedExaminationsRoute
  '/_authenticated/fee': typeof AuthenticatedFeeRoute
  '/_authenticated/hostel': typeof AuthenticatedHostelRoute
  '/_authenticated/hr': typeof AuthenticatedHrRoute
  '/_authenticated/interviews': typeof AuthenticatedInterviewsRoute
  '/_authenticated/inventory': typeof AuthenticatedInventoryRoute
  '/_authenticated/library': typeof AuthenticatedLibraryRoute
  '/_authenticated/medical': typeof AuthenticatedMedicalRoute
  '/_authenticated/payroll': typeof AuthenticatedPayrollRoute
  '/_authenticated/securities': typeof AuthenticatedSecuritiesRoute
  '/_authenticated/students': typeof AuthenticatedStudentsRoute
  '/_authenticated/teacher-diary': typeof AuthenticatedTeacherDiaryRoute
  '/_authenticated/timetable': typeof AuthenticatedTimetableRoute
  '/_authenticated/transport': typeof AuthenticatedTransportRoute
  '/auth_/$school': typeof AuthSchoolRoute
  '/_authenticated/settings/': typeof AuthenticatedSettingsIndexRoute
  '/_authenticated/m/$module/$page': typeof AuthenticatedMModulePageRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/reset-password'
    | '/accounts'
    | '/attendance'
    | '/certificates'
    | '/classes'
    | '/communication'
    | '/competition'
    | '/dashboard'
    | '/enquiry'
    | '/events'
    | '/examinations'
    | '/fee'
    | '/hostel'
    | '/hr'
    | '/interviews'
    | '/inventory'
    | '/library'
    | '/medical'
    | '/payroll'
    | '/securities'
    | '/students'
    | '/teacher-diary'
    | '/timetable'
    | '/transport'
    | '/auth/$school'
    | '/settings/'
    | '/m/$module/$page'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/reset-password'
    | '/accounts'
    | '/attendance'
    | '/certificates'
    | '/classes'
    | '/communication'
    | '/competition'
    | '/dashboard'
    | '/enquiry'
    | '/events'
    | '/examinations'
    | '/fee'
    | '/hostel'
    | '/hr'
    | '/interviews'
    | '/inventory'
    | '/library'
    | '/medical'
    | '/payroll'
    | '/securities'
    | '/students'
    | '/teacher-diary'
    | '/timetable'
    | '/transport'
    | '/auth/$school'
    | '/settings'
    | '/m/$module/$page'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/reset-password'
    | '/_authenticated/accounts'
    | '/_authenticated/attendance'
    | '/_authenticated/certificates'
    | '/_authenticated/classes'
    | '/_authenticated/communication'
    | '/_authenticated/competition'
    | '/_authenticated/dashboard'
    | '/_authenticated/enquiry'
    | '/_authenticated/events'
    | '/_authenticated/examinations'
    | '/_authenticated/fee'
    | '/_authenticated/hostel'
    | '/_authenticated/hr'
    | '/_authenticated/interviews'
    | '/_authenticated/inventory'
    | '/_authenticated/library'
    | '/_authenticated/medical'
    | '/_authenticated/payroll'
    | '/_authenticated/securities'
    | '/_authenticated/students'
    | '/_authenticated/teacher-diary'
    | '/_authenticated/timetable'
    | '/_authenticated/transport'
    | '/auth_/$school'
    | '/_authenticated/settings/'
    | '/_authenticated/m/$module/$page'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  AuthSchoolRoute: typeof AuthSchoolRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/accounts': {
      id: '/_authenticated/accounts'
      path: '/accounts'
      fullPath: '/accounts'
      preLoaderRoute: typeof AuthenticatedAccountsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/attendance': {
      id: '/_authenticated/attendance'
      path: '/attendance'
      fullPath: '/attendance'
      preLoaderRoute: typeof AuthenticatedAttendanceRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/certificates': {
      id: '/_authenticated/certificates'
      path: '/certificates'
      fullPath: '/certificates'
      preLoaderRoute: typeof AuthenticatedCertificatesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/classes': {
      id: '/_authenticated/classes'
      path: '/classes'
      fullPath: '/classes'
      preLoaderRoute: typeof AuthenticatedClassesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/communication': {
      id: '/_authenticated/communication'
      path: '/communication'
      fullPath: '/communication'
      preLoaderRoute: typeof AuthenticatedCommunicationRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/competition': {
      id: '/_authenticated/competition'
      path: '/competition'
      fullPath: '/competition'
      preLoaderRoute: typeof AuthenticatedCompetitionRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/enquiry': {
      id: '/_authenticated/enquiry'
      path: '/enquiry'
      fullPath: '/enquiry'
      preLoaderRoute: typeof AuthenticatedEnquiryRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/events': {
      id: '/_authenticated/events'
      path: '/events'
      fullPath: '/events'
      preLoaderRoute: typeof AuthenticatedEventsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/examinations': {
      id: '/_authenticated/examinations'
      path: '/examinations'
      fullPath: '/examinations'
      preLoaderRoute: typeof AuthenticatedExaminationsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/fee': {
      id: '/_authenticated/fee'
      path: '/fee'
      fullPath: '/fee'
      preLoaderRoute: typeof AuthenticatedFeeRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/hostel': {
      id: '/_authenticated/hostel'
      path: '/hostel'
      fullPath: '/hostel'
      preLoaderRoute: typeof AuthenticatedHostelRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/hr': {
      id: '/_authenticated/hr'
      path: '/hr'
      fullPath: '/hr'
      preLoaderRoute: typeof AuthenticatedHrRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/interviews': {
      id: '/_authenticated/interviews'
      path: '/interviews'
      fullPath: '/interviews'
      preLoaderRoute: typeof AuthenticatedInterviewsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/inventory': {
      id: '/_authenticated/inventory'
      path: '/inventory'
      fullPath: '/inventory'
      preLoaderRoute: typeof AuthenticatedInventoryRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/library': {
      id: '/_authenticated/library'
      path: '/library'
      fullPath: '/library'
      preLoaderRoute: typeof AuthenticatedLibraryRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/medical': {
      id: '/_authenticated/medical'
      path: '/medical'
      fullPath: '/medical'
      preLoaderRoute: typeof AuthenticatedMedicalRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/payroll': {
      id: '/_authenticated/payroll'
      path: '/payroll'
      fullPath: '/payroll'
      preLoaderRoute: typeof AuthenticatedPayrollRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/securities': {
      id: '/_authenticated/securities'
      path: '/securities'
      fullPath: '/securities'
      preLoaderRoute: typeof AuthenticatedSecuritiesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/students': {
      id: '/_authenticated/students'
      path: '/students'
      fullPath: '/students'
      preLoaderRoute: typeof AuthenticatedStudentsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/teacher-diary': {
      id: '/_authenticated/teacher-diary'
      path: '/teacher-diary'
      fullPath: '/teacher-diary'
      preLoaderRoute: typeof AuthenticatedTeacherDiaryRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/timetable': {
      id: '/_authenticated/timetable'
      path: '/timetable'
      fullPath: '/timetable'
      preLoaderRoute: typeof AuthenticatedTimetableRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/transport': {
      id: '/_authenticated/transport'
      path: '/transport'
      fullPath: '/transport'
      preLoaderRoute: typeof AuthenticatedTransportRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/auth_/$school': {
      id: '/auth_/$school'
      path: '/auth/$school'
      fullPath: '/auth/$school'
      preLoaderRoute: typeof AuthSchoolRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/settings/': {
      id: '/_authenticated/settings/'
      path: '/settings'
      fullPath: '/settings/'
      preLoaderRoute: typeof AuthenticatedSettingsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/m/$module/$page': {
      id: '/_authenticated/m/$module/$page'
      path: '/m/$module/$page'
      fullPath: '/m/$module/$page'
      preLoaderRoute: typeof AuthenticatedMModulePageRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAccountsRoute: typeof AuthenticatedAccountsRoute
  AuthenticatedAttendanceRoute: typeof AuthenticatedAttendanceRoute
  AuthenticatedCertificatesRoute: typeof AuthenticatedCertificatesRoute
  AuthenticatedClassesRoute: typeof AuthenticatedClassesRoute
  AuthenticatedCommunicationRoute: typeof AuthenticatedCommunicationRoute
  AuthenticatedCompetitionRoute: typeof AuthenticatedCompetitionRoute
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedEnquiryRoute: typeof AuthenticatedEnquiryRoute
  AuthenticatedEventsRoute: typeof AuthenticatedEventsRoute
  AuthenticatedExaminationsRoute: typeof AuthenticatedExaminationsRoute
  AuthenticatedFeeRoute: typeof AuthenticatedFeeRoute
  AuthenticatedHostelRoute: typeof AuthenticatedHostelRoute
  AuthenticatedHrRoute: typeof AuthenticatedHrRoute
  AuthenticatedInterviewsRoute: typeof AuthenticatedInterviewsRoute
  AuthenticatedInventoryRoute: typeof AuthenticatedInventoryRoute
  AuthenticatedLibraryRoute: typeof AuthenticatedLibraryRoute
  AuthenticatedMedicalRoute: typeof AuthenticatedMedicalRoute
  AuthenticatedPayrollRoute: typeof AuthenticatedPayrollRoute
  AuthenticatedSecuritiesRoute: typeof AuthenticatedSecuritiesRoute
  AuthenticatedStudentsRoute: typeof AuthenticatedStudentsRoute
  AuthenticatedTeacherDiaryRoute: typeof AuthenticatedTeacherDiaryRoute
  AuthenticatedTimetableRoute: typeof AuthenticatedTimetableRoute
  AuthenticatedTransportRoute: typeof AuthenticatedTransportRoute
  AuthenticatedSettingsIndexRoute: typeof AuthenticatedSettingsIndexRoute
  AuthenticatedMModulePageRoute: typeof AuthenticatedMModulePageRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAccountsRoute: AuthenticatedAccountsRoute,
  AuthenticatedAttendanceRoute: AuthenticatedAttendanceRoute,
  AuthenticatedCertificatesRoute: AuthenticatedCertificatesRoute,
  AuthenticatedClassesRoute: AuthenticatedClassesRoute,
  AuthenticatedCommunicationRoute: AuthenticatedCommunicationRoute,
  AuthenticatedCompetitionRoute: AuthenticatedCompetitionRoute,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedEnquiryRoute: AuthenticatedEnquiryRoute,
  AuthenticatedEventsRoute: AuthenticatedEventsRoute,
  AuthenticatedExaminationsRoute: AuthenticatedExaminationsRoute,
  AuthenticatedFeeRoute: AuthenticatedFeeRoute,
  AuthenticatedHostelRoute: AuthenticatedHostelRoute,
  AuthenticatedHrRoute: AuthenticatedHrRoute,
  AuthenticatedInterviewsRoute: AuthenticatedInterviewsRoute,
  AuthenticatedInventoryRoute: AuthenticatedInventoryRoute,
  AuthenticatedLibraryRoute: AuthenticatedLibraryRoute,
  AuthenticatedMedicalRoute: AuthenticatedMedicalRoute,
  AuthenticatedPayrollRoute: AuthenticatedPayrollRoute,
  AuthenticatedSecuritiesRoute: AuthenticatedSecuritiesRoute,
  AuthenticatedStudentsRoute: AuthenticatedStudentsRoute,
  AuthenticatedTeacherDiaryRoute: AuthenticatedTeacherDiaryRoute,
  AuthenticatedTimetableRoute: AuthenticatedTimetableRoute,
  AuthenticatedTransportRoute: AuthenticatedTransportRoute,
  AuthenticatedSettingsIndexRoute: AuthenticatedSettingsIndexRoute,
  AuthenticatedMModulePageRoute: AuthenticatedMModulePageRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  AuthSchoolRoute: AuthSchoolRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
